add missing fastcgi_cache_key in nginx; change nginx.init based latest version; fix web/web__lib.php for cp; back to execute disable-mysql-aio in install process; disable-mysql-aio only process for openvz only

diff --git a/kloxo/file/nginx/etc/init.d/nginx.init b/kloxo/file/nginx/etc/init.d/nginx.init
--- a/kloxo/file/nginx/etc/init.d/nginx.init
+++ b/kloxo/file/nginx/etc/init.d/nginx.init
@@ -1,149 +1,161 @@
 #!/bin/sh
 #
-# nginx - this script starts and stops the nginx daemon
+# nginx        Startup script for nginx
 #
-# chkconfig:   - 85 15
-# description:  Nginx is an HTTP(S) server, HTTP(S) reverse \
-#               proxy and IMAP/POP3 proxy server
+# chkconfig: - 85 15
 # processname: nginx
-# config:      /etc/nginx/nginx.conf
-# config:      /etc/sysconfig/nginx
-# pidfile:     /var/run/nginx.pid
+# config: /etc/nginx/nginx.conf
+# config: /etc/sysconfig/nginx
+# pidfile: /var/run/nginx.pid
+# description: nginx is an HTTP and reverse proxy server
+#
+### BEGIN INIT INFO
+# Provides: nginx
+# Required-Start: $local_fs $remote_fs $network
+# Required-Stop: $local_fs $remote_fs $network
+# Default-Start: 2 3 4 5
+# Default-Stop: 0 1 6
+# Short-Description: start and stop nginx
+### END INIT INFO
 
 # Source function library.
 . /etc/rc.d/init.d/functions
 
-# Source networking configuration.
-. /etc/sysconfig/network
+if [ -L $0 ] ; then
+    initscript=$(/bin/readlink -f $0)
+else
+    initscript=$0
+fi
 
-[ -f /etc/sysconfig/nginx ] && . /etc/sysconfig/nginx
+sysconfig=$(/bin/basename $initscript)
 
-# Check that networking is up.
-[ "$NETWORKING" = "no" ] && exit 0
+if [ -f /etc/sysconfig/${sysconfig} ] ; then
+    . /etc/sysconfig/${sysconfig}
+fi
 
 if [ -f /opt/nginx/usr/sbin/nginx ] ; then
-	nginx="/opt/nginx/usr/sbin/nginx"
+	nginx=${NGINX-/opt/nginx/usr/sbin/nginx}
 else
-	nginx="/usr/sbin/nginx"
+	nginx=${NGINX-/usr/sbin/nginx}
 fi
 
 prog=$(basename $nginx)
+conffile=${CONFFILE-/etc/nginx/nginx.conf}
+lockfile=${LOCKFILE-/var/lock/subsys/nginx}
+pidfile=${PIDFILE-/var/run/nginx.pid}
+SLEEPMSEC=${SLEEPMSEC-200000}
+UPGRADEWAITLOOPS=${UPGRADEWAITLOOPS-5}
+RETVAL=0
 
-NGINX_CONF_FILE="/etc/nginx/nginx.conf"
-
-lockfile=/var/lock/subsys/nginx
-
-[ -f /etc/sysconfig/custom.nginx ] && . /etc/sysconfig/custom.nginx
+if [ -f /etc/sysconfig/custom.${sysconfig} ] ; then
+    . /etc/sysconfig/custom.${sysconfig}
+fi
 
 start() {
-    [ -x $nginx ] || exit 5
-    [ -f $NGINX_CONF_FILE ] || exit 6
-    echo -n $"Starting $prog: "
-    daemon $nginx -c $NGINX_CONF_FILE
-    retval=$?
+    echo -n $"Starting ${prog}: "
+
+    daemon --pidfile=${pidfile} ${nginx} -c ${conffile}
+    RETVAL=$?
     echo
-    [ $retval -eq 0 ] && touch $lockfile
-    return $retval
+    [ $RETVAL = 0 ] && touch ${lockfile}
+    return $RETVAL
 }
 
 stop() {
-    echo -n $"Stopping $prog: "
-    killproc $prog -TERM
-    retval=$?
-    if [ $retval -eq 0 ]; then
-        if [ "$CONSOLETYPE" != "serial" ]; then
-           echo -en "\\033[16G"
-        fi
-        while rh_status_q
-        do
-            sleep 1
-            echo -n $"."
-        done
-        rm -f $lockfile
-    fi
+    echo -n $"Stopping ${prog}: "
+    killproc -p ${pidfile} ${prog}
+    RETVAL=$?
     echo
-    return $retval
-}
-
-restart() {
-#    configtest || return $?
-    stop
-    start
+    [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
 }
 
 reload() {
-#    configtest || return $?
-    echo -n $"Reloading $prog: "
-    killproc $nginx -HUP
-    sleep 1
+    echo -n $"Reloading ${prog}: "
+    killproc -p ${pidfile} ${prog} -HUP
     RETVAL=$?
     echo
 }
 
+upgrade() {
+    oldbinpidfile=${pidfile}.oldbin
+
+    configtest -q || return
+    echo -n $"Starting new master ${prog}: "
+    killproc -p ${pidfile} ${prog} -USR2
+    echo
+
+    for i in $(/usr/bin/seq $UPGRADEWAITLOOPS) ; do
+        /bin/usleep $SLEEPMSEC
+        if [ -f ${oldbinpidfile} -a -f ${pidfile} ] ; then
+            echo -n $"Graceful shutdown of old ${prog}: "
+            killproc -p ${oldbinpidfile} ${prog} -QUIT
+            RETVAL=$?
+            echo
+            return
+        fi
+    done
+
+    echo $"Upgrade failed!"
+    RETVAL=1
+}
+
 configtest() {
-  $nginx -t -c $NGINX_CONF_FILE
+    if [ "$#" -ne 0 ] ; then
+        case "$1" in
+            -q)
+                FLAG=$1
+                ;;
+            *)
+                ;;
+        esac
+        shift
+    fi
+    ${nginx} -t -c ${conffile} $FLAG
+    RETVAL=$?
+    return $RETVAL
 }
 
 rh_status() {
-    status $prog
+    status -p ${pidfile} ${nginx}
 }
 
-rh_status_q() {
-    rh_status >/dev/null 2>&1
-}
-
-# Upgrade the binary with no downtime.
-upgrade() {
-    local pidfile="/var/run/${prog}.pid"
-    local oldbin_pidfile="${pidfile}.oldbin"
-
-    configtest || return $?
-    echo -n $"Staring new master $prog: "
-    killproc $nginx -USR2
-    sleep 1
-    retval=$?
-    echo 
-    if [[ -f ${oldbin_pidfile} && -f ${pidfile} ]];  then
-        echo -n $"Graceful shutdown of old $prog: "
-        killproc -p ${oldbin_pidfile} -TERM
-        sleep 1
-        retval=$?
-        echo 
-        return 0
-    else
-        echo $"Something bad happened, manual intervention required, maybe restart?"
-        return 1
-    fi
-}
-
+# See how we were called.
 case "$1" in
     start)
-        rh_status_q && exit 0
-        $1
+        rh_status >/dev/null 2>&1 && exit 0
+        start
         ;;
     stop)
-        rh_status_q || exit 0
-        $1
+        stop
         ;;
-    restart|configtest)
-        $1
+    status)
+        rh_status
+        RETVAL=$?
         ;;
-    force-reload|upgrade) 
-        rh_status_q || exit 7
+    restart)
+        configtest -q || exit $RETVAL
+        stop
+        start
+        ;;
+    upgrade)
+        rh_status >/dev/null 2>&1 || exit 0
         upgrade
         ;;
-    reload)
-        rh_status_q || exit 7
-        $1
-        ;;
-    status|status_q)
-        rh_$1
-        ;;
     condrestart|try-restart)
-        rh_status_q || exit 7
-        restart
-	    ;;
+        if rh_status >/dev/null 2>&1 ; then
+            stop
+            start
+        fi
+        ;;
+    force-reload|reload)
+        reload
+        ;;
+    configtest)
+        configtest
+        ;;
     *)
-        echo $"Usage: $0 {start|stop|reload|configtest|status|force-reload|upgrade|restart}"
-        exit 2
+        echo $"Usage: ${prog} {start|stop|restart|condrestart|try-restart|force-reload|upgrade|reload|status|help|configtest}"
+        RETVAL=2
 esac
+
+exit $RETVAL
