fix httpd.init

diff --git a/kloxo/file/apache/etc/init.d/httpd.init b/kloxo/file/apache/etc/init.d/httpd.init
--- a/kloxo/file/apache/etc/init.d/httpd.init
+++ b/kloxo/file/apache/etc/init.d/httpd.init
@@ -3,8 +3,8 @@
 # httpd        Startup script for the Apache HTTP Server
 #
 # chkconfig: - 85 15
-# description: The Apache HTTP Server is an efficient and extensible  \
-#	       server implementing the current HTTP standards.
+# description: The Apache HTTP Server is an efficient and extensible
+#              server implementing the current HTTP standards.
 # processname: httpd
 # config: /etc/httpd/conf/httpd.conf
 # config: /etc/sysconfig/httpd
@@ -23,8 +23,8 @@
 # Source function library.
 . /etc/rc.d/init.d/functions
 
-if [ -f /etc/sysconfig/httpd ] ; then
-	. /etc/sysconfig/httpd
+if [ -f /etc/sysconfig/httpd ]; then
+    . /etc/sysconfig/httpd
 fi
 
 # Start httpd in the C locale by default.
@@ -46,8 +46,8 @@ pidfile=${PIDFILE-/var/run/httpd.pid}
 lockfile=${LOCKFILE-/var/lock/subsys/httpd}
 RETVAL=0
 
-if [ -f /etc/sysconfig/httpd24 ] ; then
-	. /etc/sysconfig/httpd24
+if [ -f /etc/sysconfig/httpd24 ]; then
+    . /etc/sysconfig/httpd24
 fi
 
 # The semantics of these two functions differ from the way apachectl does
@@ -55,69 +55,69 @@ fi
 # when not running is also a failure.  So we just do it the way init scripts
 # are expected to behave here.
 start() {
-	echo -n $"Starting $prog: "
-	LANG=$HTTPD_LANG daemon --pidfile=${pidfile} $httpd $OPTIONS
-	RETVAL=$?
-	echo
-	[ $RETVAL = 0 ] && touch ${lockfile}
-	return $RETVAL
+    echo -n $"Starting $prog: "
+    LANG=$HTTPD_LANG daemon --pidfile=${pidfile} $httpd $OPTIONS
+    RETVAL=$?
+    echo
+    [ $RETVAL = 0 ] && touch ${lockfile}
+    return $RETVAL
 }
 
 # When stopping httpd a delay of >10 second is required before SIGKILLing the
 # httpd parent; this gives enough time for the httpd parent to SIGKILL any
 # errant children.
 stop() {
-	echo -n $"Stopping $prog: "
-	killproc -p ${pidfile} -d 10 $httpd
-	RETVAL=$?
-	echo
-	[ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
+    echo -n $"Stopping $prog: "
+    killproc -p ${pidfile} -d 10 $httpd
+    RETVAL=$?
+    echo
+    [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
 }
 reload() {
-	echo -n $"Reloading $prog: "
-	if ! LANG=$HTTPD_LANG $httpd $OPTIONS -t >&/dev/null ; then
-		RETVAL=$?
-		echo $"not reloading due to configuration syntax error"
-		failure $"not reloading $httpd due to configuration syntax error"
-	else
-		killproc -p ${pidfile} $httpd -HUP
-		RETVAL=$?
-	fi
+    echo -n $"Reloading $prog: "
+    if ! LANG=$HTTPD_LANG $httpd $OPTIONS -t >&/dev/null; then
+        RETVAL=$?
+        echo $"not reloading due to configuration syntax error"
+        failure $"not reloading $httpd due to configuration syntax error"
+    else
+        killproc -p ${pidfile} $httpd -HUP
+        RETVAL=$?
+    fi
     echo
 }
 
 # See how we were called.
 case "$1" in
-	start)
-		start
-		;;
-	stop)
-		stop
-		;;
-	status)
-		status $httpd
-		RETVAL=$?
-		;;
-	restart)
-		stop
-		start
-		;;
-	condrestart)
-		if [ -f ${pidfile} ] ; then
-			stop
-			start
-		fi
-		;;
-	force-reload|reload)
-		reload
-		;;
-	graceful|help|configtest|fullstatus)
-		$apachectl $@
-		RETVAL=$?
-		;;
-		*)
-		echo $"Usage: $prog {start|stop|restart|condrestart|reload|status|fullstatus|graceful|help|configtest}"
-		RETVAL=3
+  start)
+    start
+    ;;
+  stop)
+    stop
+    ;;
+  status)
+    status $httpd
+    RETVAL=$?
+    ;;
+  restart)
+    stop
+    start
+    ;;
+  condrestart)
+    if [ -f ${pidfile} ] ; then
+      stop
+      start
+    fi
+    ;;
+  force-reload|reload)
+    reload
+    ;;
+  graceful|help|configtest|fullstatus)
+    $apachectl $@
+    RETVAL=$?
+    ;;
+  *)
+    echo $"Usage: $prog {start|stop|restart|condrestart|reload|status|fullstatus|graceful|help|configtest}"
+    RETVAL=3
 esac
 
 exit $RETVAL
